<?php

declare(strict_types=1);

use Infrangible\HtmlSitemap\Block\Sitemap\Catalog;
use Magento\Framework\View\TemplateEngine\Php;

/**
 * @author      Andreas Knollmann
 * @copyright   Copyright (c) 2014-2024 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

/** @var Php $this */
/** @var Catalog $block */

?>

<h3><?php echo __('Catalog'); ?></h3>

<?php echo $block->renderCategories(); ?>
<?php echo $block->getChildHtml('html_sitemap_catalog_additional'); ?>
