<?php

declare(strict_types=1);

use Infrangible\HtmlSitemap\Block\Sitemap;
use Magento\Framework\View\TemplateEngine\Php;

/**
 * @author      Andreas Knollmann
 * @copyright   Copyright (c) 2014-2024 Softwareentwicklung Andreas Knollmann
 * @license     http://www.opensource.org/licenses/mit-license.php MIT
 */

/** @var Php $this */
/** @var Sitemap $block */

?>

<?php echo $block->getChildHtml('html_sitemap_catalog'); ?>
<?php echo $block->getChildHtml('html_sitemap_sites'); ?>
<?php echo $block->getChildHtml('html_sitemap_additional'); ?>
